services:
    php:
        build: ./docker/php
        volumes:
            - .:/var/www:delegated
        depends_on:
            - database
    
    nginx:
        build: ./docker/nginx
        ports:
            - "8000:80"
        volumes:
            - ./public:/var/www/public:delegated
        depends_on:
            - php
    
    database:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        volumes:
            - database_data:/var/lib/postgresql/data:rw

volumes:
    database_data:      
