name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          script: |
            cd ${{ secrets.VPS_DEPLOY_DIR }}
            git pull origin main
            cat << 'EOF' > .env
            ${{ secrets.PROD_ENV }}
            EOF
            docker compose down
            export APP_ENV=prod
            docker compose build --build-arg APP_ENV=$APP_ENV
            docker compose up -d
            until nc -z -v -w30 database 5432; do
              echo "Waiting for database connection..."
              sleep 5
            done
            docker compose exec php php bin/console doctrine:migrations:migrate --no-interaction
            docker compose exec php npm install --no-save
            docker compose exec php npm run build      
            docker system prune -af
